### ISSUE TITLE
GOS source link incorrect

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#10]
The Links for many of the GOS samples are to https://doi.pangaea.de/10.1594/PANGAEA.854419 which is for the `Ocean Sampling Day Consortium` we should fix this as well.

![image](https://user-images.githubusercontent.com/12255688/60594338-032dab00-9da5-11e9-9cad-2cfd5d53ac55.png)

**Comment by kaiiam** [comment]
@mbomhoff the problem doesn't seem to be originating in the gos `datapackage.json` itself.

upon examination of this line on the website (shown in the picture above)

```
specimen identifier assigned by sequencing facility | ArchiveID_biosample | SAMEA3512126 |   | Link
```
where Link points incorrectly to: https://doi.pangaea.de/10.1594/PANGAEA.854419 (from OSD)

The corresponding lines in the datapackage are:

```
{
            "name": "ArchiveID_biosample",
            "type": "string",
            "format": "default",
            "rdfType": "http://purl.obolibrary.org/obo/OBI_0001901",
            "pm:unitRdfType": "",
            "pm:sourceUrl": "https://www.ncbi.nlm.nih.gov/bioproject/293636",
            "pm:measurementSourceRdfType": "",
            "pm:measurementSourceProtocolUrl": "",
            "pm:searchable": true
          },
```

Is it possible that the website code is hardwired from the OSD links? Or something similar?

Its strange because not all of the links have this problem:

```
secondary sample accession identifier assigned by the European Nucleotide Archive | ArchiveID_SRAaccession | ERS819275 |   | Link
```
for example displays the correct Link to https://www.ncbi.nlm.nih.gov/bioproject/293636 from the datapackage.

**Comment by mbomhoff** [comment]
It was a bug, I fixed it.  Thanks for catching!
