### ISSUE TITLE
niskin_profiles_pangea_apy schema in datapackage JSON

### ISSUE THREAD

**Issue by aponsero** [hurwitzlab/planet-microbe-datapackages#17]
The fields described in the Tara Ocean datapackage.json for the niskin_profiles_pangea_apy do not match the original datafile attributes nor the ontology table. @kaiiam did you use another table to generate this shema?

**Comment by kaiiam** [comment]
Thanks @aponsero for catching this, I used the niskin_profiles_pangea from APX. Upon closer examination, it appears that APY has the same first 19 fields but not the rest, hence we can remove everything after ``Sigma-theta`` @mbomhoff do you want me to do it, or will you?
