### ISSUE TITLE
double check HOT chl A

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#23]
for the 52 HOT delong and aloha timeseries samples there were a few with duplicate chl a values one of which was in the wrong units. Double check this and fix for next refresh.

**Comment by kaiiam** [comment]
We can probably just make those duplicated values non-searchable.

**Comment by kaiiam** [comment]
`HOT-DeLong` aka https://www.nature.com/articles/ismej2015221 has:

<img width="81" alt="image" src="https://user-images.githubusercontent.com/12255688/146552553-3e9e8dbe-a570-4ce6-9a7d-67bdd0e74609.png">

field name `chlorophyll a` which matches what it's suppose to be in resource `samples_paper1.tsv` and the unit is correct in the datapackage, http://purl.obolibrary.org/obo/PMO_00000155 aka ng/L. Which is on the site in final units of `microgram per liter`

<img width="839" alt="image" src="https://user-images.githubusercontent.com/12255688/146553156-06f15f1c-5cba-4057-93d0-12056c9f6ca0.png">

However the final result on the site is `73000` instead of `0.073`. Perhaps the issue is a mistake in the conversion factor? @aponsero

**Comment by aponsero** [comment]
The conversion factor between ng-->mg was handled by Matt's library at upload. So it should be good. Is it correct for other samples with that measure?

**Comment by kaiiam** [comment]
I think it's the conversion factor in the script, see my updated version of the [file](https://github.com/hurwitzlab/planet-microbe-scripts/pull/2/files)

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/12255688/146555141-bb93b3b3-5a79-442f-8c50-8c4cdc25221f.png">

I think it's backwards should be `0.001`

**Comment by kaiiam** [comment]
```
# concentration of chlorophyll a in water				
http://purl.obolibrary.org/obo/ENVO_3100008	http://purl.obolibrary.org/obo/UO_0000301	http://purl.obolibrary.org/obo/PMO_00000155	1000	ng/L to ug/L
http://purl.obolibrary.org/obo/ENVO_3100008	http://purl.obolibrary.org/obo/UO_0000301	http://purl.obolibrary.org/obo/PMO_00000132	1	mg/m^3 to _g/L
http://purl.obolibrary.org/obo/ENVO_3100008	http://purl.obolibrary.org/obo/UO_0000301	http://purl.obolibrary.org/obo/UO_0000064	893.5	micromolar to ug/L
http://purl.obolibrary.org/obo/ENVO_3100008	http://purl.obolibrary.org/obo/UO_0000301	http://purl.obolibrary.org/obo/PMO_00000178	0.0010236	nanogram per kilogram to microgram per liter
```

The last line for `nanogram per kilogram to microgram per liter` is `0.0010236` going from nano to micro.

**Comment by kaiiam** [comment]
I'll check the others to be sure/make sure weren't not missing something

`HOT_DeLong_Timedepth_series` aka https://doi.org/10.1038/s41564-017-0008-3 supplemental file has the following which matches what we have in resource `sample_paper.tsv`:

`chl` in `ug/l`
<img width="54" alt="image" src="https://user-images.githubusercontent.com/12255688/146556478-da7a3ab7-4451-437b-a9ed-53f19899f9c0.png">

we annotate this with http://purl.obolibrary.org/obo/UO_0000301 aka `microgram per liter` so this is correct.

and `hplc` in `ng/l`

<img width="55" alt="image" src="https://user-images.githubusercontent.com/12255688/146556818-cddedd49-feb8-463e-a8be-4914a07b2a41.png">

we annotated this with http://purl.obolibrary.org/obo/PMO_00000155 aka `nanogram per liter` so this is also correct.

I had specifically double checked this things prior to publishing that these things were correct chl a values in the right units.

**Comment by kaiiam** [comment]
OSD:

has one annotation sourced from https://doi.pangaea.de/10.1594/PANGAEA.854419

<img width="364" alt="image" src="https://user-images.githubusercontent.com/12255688/146558317-dbacd302-20b5-4166-9eb8-7ff55c8cc236.png">

in `mg/m^3`

which we have correctly as http://purl.obolibrary.org/obo/PMO_00000132 `miligram per cubic meter`

**Comment by kaiiam** [comment]
Tara oceans has several: but only 2 variations: 

https://doi.pangaea.de/10.1594/PANGAEA.836319 or e.g. https://doi.pangaea.de/10.1594/PANGAEA.838957 has

<img width="356" alt="image" src="https://user-images.githubusercontent.com/12255688/146559400-699d8dc5-b7c5-4f64-9b40-aceb619ca532.png">

which we have correctly as http://purl.obolibrary.org/obo/PMO_00000132 miligram per cubic meter.


https://doi.pangaea.de/10.1594/PANGAEA.836319 aka https://doi.pangaea.de/10.1594/PANGAEA.838957 has 

`TChl a` 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/12255688/146560697-1bc6ff87-5b9b-4eb8-a777-a46e6857152c.png">

which we have correct as well http://purl.obolibrary.org/obo/UO_0000301 aka `microgram per liter`

Therefore I think the only mistake is the above bug in the conversion factor in the script

**Comment by aponsero** [comment]
Ok, then it means that the conversion sheet needs to be updated.

**Comment by kaiiam** [comment]
Should now be fixed with https://github.com/hurwitzlab/planet-microbe-scripts/pull/2/commits/71f79baf8138ddc772d0981ac63c233bac96a3e9
