### ISSUE TITLE
Create HOT-DeLong datapackage

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#3]
Next datapackage to create will be the HOT-DeLong datapackage, which I will try to get to this week. @mbomhoff  had suggested that if I don't get it done in time he or @aponsero  could create it without all the ontology terms, and I could go back later. 

I will try to do it this week, if I don't and @mbomhoff wants it sooner he could create it and I'll fill in the ontology terms later to the datapackage.json file.

**Comment by kaiiam** [comment]
@aponsero I notice that I notice that in the ``samples_paper1`` the heterotrophic   bacteria cell counts, Prochlorococcus cell counts, Synechococcus cell counts, Picoeukaryote cell counts all have units of ``x105 cells/ml`` I assume this is time ten to the 5 cells/ml? I'm going to make this change within the data multiplying them all by *10^5, as I don't think we should have a unit of *10^5 cells/ml but rather just cells per ml. Let me know if this isn't the case and I can change it back or do it some other way?

**Comment by kaiiam** [comment]
@mbomhoff  and @aponsero I notice that in the ``samples_paper1`` the sampling Date and Time are in GMT - Greenwich Mean Time rather than, UTC which seems to be the [frictionless standard](https://pre-v1.frictionlessdata.io/json-table-schema/#date). @mbomhoff do you think we could keep it as GMT and use frictionless to convert to UTC from GMT? Or would it be better to do it manually?

**Comment by kaiiam** [comment]
I'm also unclear about the ``low-level nitrogen`` and ``low-level phosphorus`` columns. Based on the [Hot protocol](http://hahana.soest.hawaii.edu/hot/protocols/protocols.html) I see that their are protocols for a variety of things, but I can't tell from the hotdogs site or from the paper what they mean by these. Is it particulate nitrogen and phosphorus or is it phosphate and nitrate/nitrite? @aponsero do you have any ideas? Do you think we'll need to ask someone who knows the hot data better Elisha?

**Comment by mbomhoff** [comment]
@kaiiam Re. the datetimes, I can update the load script to handle the conversion.

**Comment by kaiiam** [comment]
@mbomhoff I've completed the ontology work, now I just need to make the datapackage. Once I do you may need to double check my date and time columns to make sure the format is ok, along with converting from GMT to UTC. I put the same ontology annotation term for both, perhaps that's not ideal? Would it be better to combine them into one single datetime column? Or is this the kind of think frictionless can do for us?

**Comment by mbomhoff** [comment]
@kaiiam Great!  Can you use a different onto term for date and time?  My load script can then merge them into a single datetime field.

**Comment by mbomhoff** [comment]
@kaiiam On 2nd thought, same onto term is preferable.

**Comment by kaiiam** [comment]
OK @mbomhoff I'll use the same term for now. I'll you figure out the merge/timezone changes.

**Comment by kaiiam** [comment]
datapackaged created!
