### ISSUE TITLE
Add filter_max to HOT-Chisholm Data package 

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#4]
I missed this earlier that I should add 

filter_max | upper size threshold filter paper | http://purl.obolibrary.org/obo/PMO_00000023
-- | -- | --

To the HOT-Chisholm Data package. @mbomhoff what is the best workflow for the general case of updating the datapackages? I know they can take some time to load and we'll probably find little bugs like this and or update ontology terms etc. Should I just go ahead and make the changes to the datapackages, the record of which will show up in the commit/change history and later once we decide it's complete or a next version you could load it again?

**Comment by kaiiam** [comment]
Issue dealt with, but the question stands, for changes to datapapckages @mbomhoff has already loaded should we just make changes directly to the data package file on github, and then later (once we think it's complete or more complete) load the datapackage again?

**Comment by mbomhoff** [comment]
Yes, it's not a problem for me to reload the datapackage each time there are changes.

**Comment by kaiiam** [comment]
Sounds good.
