### ISSUE TITLE
HOT Delong missing metadata in schema

### ISSUE THREAD

**Issue by aponsero** [hurwitzlab/planet-microbe-datapackages#5]
@kaiiam 
So, part of the issue was me, I forgot to remove empty columns (or column full of "nd") from the file, sorry. But there are few terms that are still missing. Unfortunately I don't find some of the purls for them in the other package (NITRATE and PP from BCO-DMO). If you just give me the purls I can add them and update the datapackage.

Missing PURLS in :

-CTD_profiles.tsv
NITRATE

-Niskin_profiles.tsv
PP

-samples_CTD_BCO-DMO.tsv
sample_name
NITRATE

-samples_Niskin_BCO-DMO.tsv
cruise_expedition
sample_name

**Comment by kaiiam** [comment]
Hey @aponsero 

``NITRATE`` (no3 not nox) http://purl.obolibrary.org/obo/ENVO_3100022

``sample_name`` http://purl.obolibrary.org/obo/OBI_0001900

 ``cruise_expedition`` 	http://purl.obolibrary.org/obo/PMO_00000007


Also I noticed that in  HOT-DeLong/ontologies/samples_Niskin_BCO-DMO.tsv you added some blank lines followed by what appears to be a header, was this on purpose? if not could you remove it?

**Comment by aponsero** [comment]
@kaiiam Thanks,
There is also the "PP" from BCO-DMO that I didn't have

**Comment by kaiiam** [comment]
Yes, I'll see if I have one for it, if not I will add it later

**Comment by aponsero** [comment]
ok ! I'll fix the blank line, thanks !

**Comment by kaiiam** [comment]
I had created the class ``primary productivity carbon`` http://purl.obolibrary.org/obo/PMO_00000108 for primary productivity measured in some units of carbon.  I don't see the units for PP in https://o.com/hurwitzlab/planet-microbe-datapackages/blob/master/HOT-DeLong/ontologies/Niskin_profiles.tsv

Do you know what they were supposed to be in?

**Comment by aponsero** [comment]
According to BCO-DMO it is in nanomole per kilogram (nmol/kg)

**Comment by kaiiam** [comment]
Great you can use ``nanomole per kilogram`` http://purl.obolibrary.org/obo/PMO_00000154 which I created for this. It's strange I had created these terms but perhaps I forgot to put them in, or perhaps the file was changed? I hope we have it sorted now and didn't louse anything.

**Comment by aponsero** [comment]
I think it is because we assumed that the BCO-DMO fields would be the same as the HOT Chisholm, but in fact they are slightly different... 

Thanks for the purls, I am adding that and fixing the weird character in the name of the biosample. And we should be good to go.

**Comment by kaiiam** [comment]
Great, thanks @aponsero close when finished.
