### ISSUE TITLE
licenses

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#6]
I noticed that we don't have licenses in any of the HOT (Delong, Chisholm and now Delong_metatranscritomes) datapackages.json files. 

In OSD we have the license:

```
  "licenses": [
    {
      "name": "CC-BY-3.0",
      "title": "Creative Commons Attribution 3.0 Unported",
      "path": "https://creativecommons.org/licenses/by/3.0/"
    }
],
```

@mbomhoff could we use this license for the other 3 Hot datasets?

**Comment by mbomhoff** [comment]
The OSD license info is from the PANGEA page:  https://doi.pangaea.de/10.1594/PANGAEA.854419
I wasn't able to find license info for the HOT datasets.  Maybe just need to look harder.

**Comment by kaiiam** [comment]
I also wasn't able to find a license for the GOS ``Beyster Family Fund and Life Technologies Foundation-funded Global Ocean Sampling Expedition, 2009-2011`` dataset

**Comment by mbomhoff** [comment]
I think it's better to leave the license blank or assign "public domain" if none.

**Comment by kaiiam** [comment]
I think we fixed this a while back as they now all have 

```
  "licenses": [
    {
      "name": "CC-BY-3.0",
      "title": "Creative Commons Attribution 3.0 Unported",
      "path": "https://creativecommons.org/licenses/by/3.0/"
    }
  ],
```
