### ISSUE TITLE
metatranscriptome type

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#7]
for the pm:projectType field in the HOT_Delong_metatranscriptomes datapackage.json I put:

```
"pm:projectType": "marine metatranscriptome",
```

@mbomhoff  I'm not sure if that's what we were planning on using to differentiate metagenomes from metatranscriptomes. Let me know your thoughts eventually we could find/make purls to differentiate but for now are we just going to use strings in pm:projectType"?

**Comment by mbomhoff** [comment]
I added that field to have a standard way to represent that information but PURLs would be great.
