### ISSUE TITLE
HOT DeLong Metatranscriptomes ether?

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-datapackages#8]
see an example: https://www.planetmicrobe.org/project/#/samples/1590

Chebi ether http://purl.obolibrary.org/obo/CHEBI_25698 are annotated for chlorophyll c, which shows up repeatedly. We should fix this.

**Comment by kaiiam** [comment]
Same issue in all HOT datapackages as well as GOS. 

HOT Chisholm:

![image](https://user-images.githubusercontent.com/12255688/60593986-3e7baa00-9da4-11e9-9e07-dce3cf4790a5.png)

 HOT DeLong Metatranscriptomes:

![image](https://user-images.githubusercontent.com/12255688/60594097-7e429180-9da4-11e9-8124-12dd49372787.png)

**Comment by kaiiam** [comment]
Upon examination of the HOT DeLong Metatranscriptomes there is no purl for ether http://purl.obolibrary.org/obo/CHEBI_25698. I'm unclear as to what is causing the issue. @mbomhoff any ideas?

**Comment by kaiiam** [comment]
In #11 I added the filter min and max purls in-case that helps with this issue.

**Comment by mbomhoff** [comment]
Due to a weird bug, now fixed!
